AlexY - Initial commit, passed state property everywhere to extract p…
sergei-startsev/babel-plugin-react-displayname-path pull request #1
Opened 2019-06-19 10:38 UTC by aliaksandr-yermalayeu

…ath and set it to displayName

2019-06-19 11:04 UTC, sergei-startsev commented on index.js
> +  var url = pathMod.relative(state.cwd, state.filename).replace(/\\/g, "/");
Could you rename `url` to `modulePath`?

2019-06-19 11:04 UTC, sergei-startsev commented on index.js
> +  displayName = `${displayName} (${url})`;
maybe update `componentNameFromFilename` function and use it here? I don't see that this function is used anywhere...

2019-06-19 11:05 UTC, sergei-startsev commented
Have you run tests? Could you also update them?

2019-06-19 11:10 UTC, sergei-startsev requested changes
Have you run tests? Could you also update them?

2019-06-19 17:46 UTC, asapach requested changes

2019-06-19 17:46 UTC, asapach commented on package.json
>    "version": "0.0.5",
you also need to update name and version

2019-06-19 17:46 UTC, asapach commented on package.json
>    "author": "Ron Cohen",
and maybe do something with author? https://docs.npmjs.com/files/package.json#people-fields-author-contributors

2019-06-19 17:46 UTC, asapach commented on test/fixtures/classComponents/expected.js
> +function _defineProperty(obj, key, value) { if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } ret
this is strange - where is it being used?

2019-06-19 17:46 UTC, asapach commented on test/fixtures/decorators/expected.js
> +let DecoratedComponent = _decorate([connect(Component)], function (_initialize, _React$Component) {
omfg

is there an option to use something like https://babeljs.io/docs/en/babel-runtime?
or just delete this test

2019-06-19 17:46 UTC, asapach commented on test/tests.js
> +      ['@babel/plugin-proposal-class-properties']
is it actually being used anywhere?

2019-06-20 18:26 UTC, asapach commented
BTW, does this work with [memo](https://reactjs.org/docs/react-api.html#reactmemo)? I see people using it and the `displayName` is essentially useless. I think we need a test for this.

2019-06-23 17:40 UTC, sergei-startsev approved these changes

2019-06-23 17:46 UTC, merged

2019-06-23 17:47 UTC, sergei-startsev commented
Merged PR to unlock further changes.